### ISSUE TITLE
Search only at initialization

### ISSUE THREAD

**Issue by hori-ryota** [Shougo/ddu-ui-filer#17]
# Problems summary

Since [searchItem is executed every redraw](https://github.com/Shougo/ddu-ui-filer/blob/331b70ab12de5395e5d64630186020de24277c88/denops/%40ddu-uis/filer.ts#L403-L408) , cursor moves even when executing `toggleSelectItem` etc.

## Expected

Keep cursor at position where the action was executed (search only at ddu starting (even with resume option)).

## Environment Information

- ddu-ui-filer version (SHA1):

`331b70ab12de5395e5d64630186020de24277c88`

- denops.vim version (SHA1):

`6578820fb79b1ae45e0dd448fd96dd6deb2f7be0`

- deno version(`deno -V` output):

`deno 1.28.3`

- OS:

`macOS 12.6.2`

- neovim/Vim `:version` output:

```
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set runtimepath+=path/to/denops.vim
set runtimepath+=path/to/ddu.vim
set runtimepath+=path/to/ddu-ui-filer
set runtimepath+=path/to/ddu-column-filename
set runtimepath+=path/to/ddu-source-file
set runtimepath+=path/to/ddu-kind-file

nnoremap <silent> <space>e <Cmd>call ddu#start({
      \   'ui': 'filer',
      \   'sync': v:true,
      \   'sources': [{
      \     'name': 'file',
      \     'options': {
      \       'path': getcwd(),
      \       'columns': ['filename'],
      \     },
      \   }],
      \   'uiParams': {
      \     'filer': {
      \       'search': 'abspath/to/a/file'
      \     },
      \   },
      \ })<CR>

nnoremap <silent> <space>x <Cmd>call ddu#ui#filer#do_action('toggleSelectItem')<CR>
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. (prepare) create multiple files at your workspace
2. Open ddu filer with `search` uiParams with a file ( `<space>e` )
3. Execute `toggleSelectItem` to other file ( `<space>x` )

## Screenshot (if possible)

When select `LICENSE` cursor was moved to `search` path item ( `README.md` ).

<img width="111" alt="Screen Shot 2023-01-10 at 13 11 10" src="https://user-images.githubusercontent.com/2936501/211460183-4dec0d7c-573d-47d3-862d-d5111d5f2b8f.png">

**Comment by hori-ryota** [comment]
uiParamsではなく独立した `recursiveSearch` みたいなメソッドが生やせれば他の用途でも嬉しいと思いましたが、ddu-ui-filerだけでなくddu本体にui actionを増やすか否かの話になりそうなのでいったん現在の困りごとだけissue化してみました。

**Comment by Shougo** [comment]
"ddu-ui-filer-param-search" is removed.  Please use "ddu-option-searchPath"  instead.

**Comment by hori-ryota** [comment]
[Level 1 items are displayed multiple times when redrawing with nested \(expanded 1 level or more deep\) items · Issue \#16 · Shougo/ddu\-ui\-filer](https://github.com/Shougo/ddu-ui-filer/issues/16)

に同じくこちらも起動時に深い階層のpathを "ddu-option-searchPath" に指定してもexpandしなくなっていますよね。
`searchPath` メソッドを調整できないか試してみます

**Comment by hori-ryota** [comment]
expandするようにしてみました。

[searchPath with expand by hori\-ryota · Pull Request \#19 · Shougo/ddu\-ui\-filer](https://github.com/Shougo/ddu-ui-filer/pull/19)
