### ISSUE TITLE
When 'split' is set to 'no', new buffer was created after quitted

### ISSUE THREAD

**Issue by namutaka** [Shougo/ddu-ui-filer#27]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

When `split` option is set to 'no', after I quitted ddu, new "No Name" buffer was created.

## Expected

"No Name" buffer is not created.

## Environment Information

- ddu-ui-filer version (SHA1): 61c76a14d04e3d3191c645e75a0e9400ce1252a4

- denops.vim version (SHA1): 8f3899de3d3add07105221262dca90a31c4c2d4c

- deno version(`deno -V` output): `deno 1.32.2`

- OS: Mac

- neovim/Vim `:version` output:
```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/denops.vim
set runtimepath+=~/path/to/ddu.vim
set runtimepath+=~/path/to/ddu-source-file
set runtimepath+=~/path/to/ddu-ui-filer

nnoremap <space>e <Cmd>call ddu#start({
      \   'ui': 'filer',
      \   'sources': [{ 'name': 'file', 'params': {} }],
      \   'uiParams': {
      \     'filer': {
      \       'split': 'no',
      \     },
      \   },
      \ })<CR>

nnoremap <space>x <Cmd>call ddu#ui#filer#do_action('quit')<CR>

```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Open "No Name" buffer
2. Check buffer list (`:ls`)
```
:ls
  1 %a   "[No Name]"                    line 1
```
3. Open ddu filer (`<space>e`)
4. Close ddu filer (`<space>x`)
5. Check buffer list again (`:ls`)
```
:ls
  1  h   "[No Name]"                    line 1
  3 %a   "[No Name]"                    line 1
```

**Comment by Shougo** [comment]
Fixed.
