### ISSUE TITLE
Strange (unexpected) behavior If specify 'topleft' to splitDirection

### ISSUE THREAD

**Issue by ryota2357** [Shougo/ddu-ui-filer#33]
# Problems summary

If I specify `splitDirection: 'topleft'`, several unexpected behaviors occur (please see reproduce section).

## Expected

Works same as `splitDirection: 'belowright'`

## Environment Information

- ddu-ui-filer version (SHA1): 27b2ffe11660074145e3e8b4831a695932cf4f04 (latest)
- denops.vim version (SHA1): ea7370bf5d323e83ee13ccba35f56e06db5753e1 (latest)
- deno version(`deno -V` output):
```
deno 1.37.2 (release, aarch64-apple-darwin)
v8 11.8.172.13
typescript 5.2.2
```
- OS: MacOS
- neovim/Vim `:version` output:
```
NVIM v0.10.0-dev-1428+g7a5effb0f-Homebrew
Build type: Release
LuaJIT 2.1.1696795921
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
if !has("nvim")
  set nocompatible
  filetype plugin indent on
  syntax enable
endif

let s:plugins = [
      \ 'vim-denops/denops.vim',
      \ 'Shougo/ddu.vim',
      \ 'Shougo/ddu-ui-filer',
      \ 'ryota2357/ddu-column-icon_filename',
      \ 'Shougo/ddu-source-file',
      \ 'Shougo/ddu-kind-file',
      \ ]
for item in s:plugins
  execute 'set runtimepath+=~/.cache/dein/repos/github.com/' .. item
endfor

call ddu#custom#patch_global(#{
    \   ui: 'filer',
    \   sources: [{'name': 'file'}],
    \   sourceOptions: #{
    \     _: { 'columns': ['icon_filename'] }
    \   },
    \   uiOptions: #{
    \     _: #{ toggle: v:true }
    \   },
    \   uiParams: #{
    \     _: #{ splitDirection: 'topleft' }
    \   },
    \   kindOptions: #{
    \     file: #{
    \       defaultAction: 'open',
    \     },
    \   }
    \ })

autocmd FileType ddu-filer call s:ddu_my_settings()
function! s:ddu_my_settings() abort
  nnoremap <buffer><CR> <Cmd>call ddu#ui#sync_action('itemAction')<CR>
  nnoremap <buffer>o    <Cmd>call ddu#ui#async_action('itemAction', #{ params: #{ command: 'tab drop' } })<CR>
endfunction

```

### `toggle` does not works.
- `:call ddu#start()` then open filer.
- `:call ddu#start()` to close filer.
- You can see that the filer is not closed and the another buffer is closed.

https://github.com/Shougo/ddu-ui-filer/assets/61523777/049d47d9-f04b-47f7-81ea-cfddf3ddeeeb

### open with tab drop
- `:call ddu#start()` then open filer.
- <kbd>CR</kbd> to open a.txt.
- `:call ddu#start()` then re-open filer.
- <kbd>o</kbd> to open b.txt with `tab drop`
- You can see that a.txt is closed and the filer buffer is remained.

https://github.com/Shougo/ddu-ui-filer/assets/61523777/7311126e-e6ec-4f00-8284-020e8a29b670

**Comment by Shougo** [comment]
Reproduced.  `close {winid}` seems broken.
I don't know why it does not work.

You can test by `close {winid}` manually.

**Comment by Shougo** [comment]
Fixed.
