### ISSUE TITLE
epanded tree are all collapsed when `updateOptions` is fired

### ISSUE THREAD

**Issue by kamecha** [Shougo/ddu-ui-filer#34]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
SSIA

## Expected
after redraw, the tree is saved.

## Environment Information

- ddu-ui-filer version (SHA1):
dba7524
- denops.vim version (SHA1):
83f167b
- deno version(`deno -V` output):
deno 1.38.5
- OS:
WSL2: Ubuntu 22.04.3
- neovim/Vim `:version` output:
NVIM v0.10.0-dev-1846+gf31f260f0
Build type: RelWithDebInfo
LuaJIT 2.1.1702233742

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=~/.cache/dein/nvim/repos/github.com/vim-denops/denops.vim

set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-ui-filer
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-source-file
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-kind-file

nnoremap [ddu] <Nop>
nmap <Space>u [ddu]
nmap <silent> [ddu]F <Cmd>call ddu#start({
			\ 'ui': 'filer',
			\ 'sources': [{'name': 'file', 'params': {}}],
			\ })<CR>

autocmd FileType ddu-filer call s:ddu_filer_my_settings()

function s:ddu_filer_my_settings() abort
	nnoremap <buffer><silent> u
				\ <Cmd>call ddu#ui#filer#do_action('updateOptions', #{
				\	uiParams: #{ 
				\		filer: #{
				\			displayRoot: v:false
				\		}
				\	}
				\ })<CR>
	nnoremap <buffer> e
				\ <Cmd>call ddu#ui#do_action('expandItem', {'mode': 'toggle'})<CR>
	nnoremap <buffer> q
				\ <Cmd>call ddu#ui#filer#do_action('quit')<CR>
endfunction
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. type `<Space>` `u` `F` to start ddu
2. type `e` to expand each item
3. type `u` to fire `updateOptions` action
4. now the item expnaded in 2 is collapsed...

## Screenshot (if possible)
![hoge](https://github.com/Shougo/ddu-ui-filer/assets/50443168/ee1298f5-4eef-4fb8-bef1-eab6fe530ae2)
## Upload the log messages by `:redir` and `:message` (if errored)

**Comment by Shougo** [comment]
I will check it later.

**Comment by Shougo** [comment]
Sorry.  This is feature.
