### ISSUE TITLE
multi_actions(['expandItem', 'cursorNext']) seems not to execute in order.

### ISSUE THREAD

**Issue by fuzakebito** [Shougo/ddu-ui-filer#38]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
It is intended to sequentially perform directory expansion and cursor movement by using multi_actions(['expandItem', 'cursorNext']), aiming to position the cursor at the first item in the expanded directory.
However, after this operation is performed, the cursor is found to be on the element next to the directory before its expansion, seems like cursor moved first and then the directory expanded afterwards.

## Expected
The directory expands, and the cursor points to the next element of the expanded directory.

## Environment Information

- ddu-ui-filer version (SHA1): from `c881d72` to latest(`0697375`)

- denops.vim version (SHA1): `2a393849

- deno version(`deno -V` output): `deno 1.43.1`

- OS: Arch Linux

- neovim/Vim `:version` output:
```
NVIM v0.10.0-dev-2961+g4d52b0cf6
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set runtimepath+=~/gomi/denops.vim
set runtimepath+=~/gomi/ddu.vim
set runtimepath+=~/gomi/ddu-ui-filer
set runtimepath+=~/gomi/ddu-source-file
nnoremap <silent> <Space>e <Cmd>call ddu#start(#{
      \   ui: 'filer',
      \   sources: [#{name:'file'}],
      \ })<CR>
nnoremap o <Cmd>call ddu#ui#multi_actions(['expandItem', 'cursorNext'])<CR>
nnoremap q <Cmd>call ddu#ui#do_action('quit')<CR>
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. \<space\>e
2. select some dir
3. o

**Comment by Shougo** [comment]
Reproduced.

**Comment by Shougo** [comment]
Fixed.
