### ISSUE TITLE
Items appear redundant when redrawn

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/ddu-ui-filer#39]
# Problems summary
Items appear redundant when redrawn.

## Expected
Items are no longer redundant when redrawn.

## Environment Information

- ddu-ui-filer version (SHA1): 94ad1d215fd48a4ef2311532a7383d44370ed53c

- denops.vim version (SHA1): bcc88ca61f1edcbe364dbfb4967204193efc6e9a

- deno version(`deno -V` output): deno 1.42.4

- OS: Linux

- neovim/Vim `:version` output: NVIM v0.10.0-dev-3023+g499070148

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

`init.lua`
```lua
vim.opt.runtimepath:prepend('~/.cache/dpp/repos/github.com/vim-denops/denops.vim')
vim.opt.runtimepath:prepend('~/.cache/dpp/repos/github.com/Shougo/ddu.vim')
vim.opt.runtimepath:prepend('~/.cache/dpp/repos/github.com/Shougo/ddu-ui-filer')
vim.opt.runtimepath:prepend('~/.cache/dpp/repos/github.com/Shougo/ddu-source-file')
vim.opt.runtimepath:prepend('~/.cache/dpp/repos/github.com/Shougo/ddu-column-filename')
vim.opt.runtimepath:prepend('~/.cache/dpp/repos/github.com/Shougo/ddu-kind-file')
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. `$ mkdir -p foo/bar`
2. `$ cd foo`
3. `$ nvim`
4. `:lua vim.fn['ddu#start'] { ui = 'filer', resume = true, sync = true, sources = { {name = 'file'} }, sourceOptions = { file = { columns = { 'filename' }, path = vim.fn.getcwd() } } }`
5. Selected bar directory.
6. `:call ddu#ui#do_action('expandItem', {'mode': 'toggle'})`
7. `:call ddu#ui#do_action('itemAction', {'name': 'newFile'})`
8. Create `hoge.txt` file.
9. `:call ddu#ui#do_action('redraw')`

## Screenshot (if possible)

![スクリーンショット 2024-05-15 034430](https://github.com/Shougo/ddu-ui-filer/assets/3197942/4e46edcb-600a-44b3-812f-8e9671693ad2)

**Comment by Shougo** [comment]
Please don't use lua script for the reproduce instruction.

**Comment by Shougo** [comment]
I have created the minimal config.

```vim
set rtp+=~/work/denops.vim
set rtp+=~/work/ddu.vim
set rtp+=~/work/ddu-ui-filer
set rtp+=~/work/ddu-source-file
set rtp+=~/work/ddu-column-filename
set rtp+=~/work/ddu-kind-file

call ddu#start(#{
      \   ui: 'filer',
      \   resume: v:true,
      \   sync: v:true,
      \   sources: [
      \     #{name: 'file'},
      \   ],
      \   sourceOptions: #{
      \     file: #{
      \       columns: ['filename'],
      \       path: getcwd()
      \     }
      \   }
      \ })

autocmd FileType ddu-filer call s:ddu_filer_my_settings()
function s:ddu_filer_my_settings() abort
  nnoremap <buffer> o
  \ <Cmd>call ddu#ui#do_action('expandItem', {'mode': 'toggle'})<CR>
  nnoremap <buffer> N
  \ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'newFile'})<CR>
  nnoremap <buffer> <C-l>
  \ <Cmd>call ddu#ui#do_action('redraw')<CR>
endfunction
```

**Comment by nabezokodaikon** [comment]
We apologize for the inconvenience.
When I performed the following steps with that vimscript, it was reproduced.

1. `$ mkdir -p foo/bar`
2. `$ cd foo`
3. `$nvim`
4. Perform `toggle` operation on filer.
5. Perform `newFile` operation with filer.
6. Perform `redraw` operation with filer.

Thank you.

**Comment by Shougo** [comment]
Fixed.  Please update ddu.vim.

**Comment by nabezokodaikon** [comment]
Thank you!
