### ISSUE TITLE
Redrawing the directory hierarchy becomes messed up

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/ddu-ui-filer#41]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
Redrawing the directory hierarchy becomes messed up.

## Expected
Redrawing correctly.

## Environment Information

- ddu-ui-filer version (SHA1):94ad1d215fd48a4ef2311532a7383d44370ed53c

- denops.vim version (SHA1):9dd9ae9da9b8d65916dd44e0e4d881665397de63

- deno version(`deno -V` output):deno 1.43.4

- OS: Linux

- neovim/Vim `:version` output:NVIM v0.10.0-dev-3023+g499070148

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=~/work/denops.vim
set rtp+=~/work/ddu.vim
set rtp+=~/work/ddu-ui-filer
set rtp+=~/work/ddu-source-file
set rtp+=~/work/ddu-column-filename
set rtp+=~/work/ddu-kind-file

call ddu#start(#{
      \   ui: 'filer',
      \   resume: v:true,
      \   sync: v:true,
      \   sources: [
      \     #{name: 'file'},
      \   ],
      \   sourceOptions: #{
      \     file: #{
      \       columns: ['filename'],
      \       path: getcwd()
      \     }
      \   }
      \ })

autocmd FileType ddu-filer call s:ddu_filer_my_settings()
function s:ddu_filer_my_settings() abort
  nnoremap <buffer> o
  \ <Cmd>call ddu#ui#do_action('expandItem', {'mode': 'toggle'})<CR>
  nnoremap <buffer> N
  \ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'newFile'})<CR>
  nnoremap <buffer> <C-l>
  \ <Cmd>call ddu#ui#do_action('redraw')<CR>
endfunction
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. `$ mkdir -p foo/bar`
2. `$ nvim`
3. Perform `foo` directory `toggle` operation on filer.
4. Perform `bar` directory `toggle` operation on filer.
5. Perform `hoge.txt` file `newFile` operation on filer.
6. Place the cursor on the `foo` directory.
7. Perform `foo` directory `toggle` operation on filer.
8. Perform `redraw` operation with filer.

## Screenshot (if possible)

![スクリーンショット 2024-05-19 002056](https://github.com/Shougo/ddu-ui-filer/assets/3197942/5d13e45a-f45f-4ff2-9c96-f8353b5d785f)

![スクリーンショット 2024-05-19 002111](https://github.com/Shougo/ddu-ui-filer/assets/3197942/d18ba605-85b6-4c2b-a1ae-4fe96ce91ca9)

**Comment by Shougo** [comment]
Fixed.  Please update ddu.vim.

**Comment by nabezokodaikon** [comment]
I confirmed it. Thank you.
