### ISSUE TITLE
If I run the action on the top 'file', I get an error.

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/ddu-ui-filer#7]
# Problems summary
If I run the action on the top 'file', I get an error.

## Expected
The text at the top should represent the current directory and should operate like any other directory.

## Environment Information

- ddu-ui-filer version (SHA1):10f5fa8d4268847e4fa5f865549443b2e2e802a8

- denops.vim version (SHA1):a40e0c10be0c67b5fd6cb9713914b9259dafa7e2

- deno version(`deno -V` output): `deno 1.24.1`

- OS: Mac

- neovim/Vim `:version` output:
```
NVIM v0.8.0-dev-2225-gb8dcbcc73
Build type: Release
LuaJIT 2.1.0-beta3
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

`~/.config/nvim/init.lua`
```lua
vim.cmd('syntax off')
vim.cmd('filetype off')
vim.cmd('filetype plugin indent off')

local cache_dir = vim.env.HOME .. '/.cache'
local dein_dir = cache_dir .. '/dein'
local dein_repo_dir = dein_dir .. '/repos/github.com/Shougo/dein.vim'

if not string.match(vim.o.runtimepath, '/dein.vim') then
	if vim.fn.isdirectory(dein_repo_dir) ~= 1 then
		os.execute('git clone https://github.com/Shougo/dein.vim ' .. dein_repo_dir)
	end
	vim.o.runtimepath = dein_repo_dir .. ',' .. vim.o.runtimepath 
end

if vim.call('dein#min#load_state', dein_dir) ~= 1 then
    return
end

vim.call('dein#begin', dein_dir)

vim.call('dein#add', 'vim-denops/denops.vim')
vim.call('dein#add', 'Shougo/ddu.vim')
vim.call('dein#add', 'Shougo/ddu-commands.vim')
vim.call('dein#add', 'Shougo/ddu-ui-filer')
vim.call('dein#add', 'Shougo/ddu-kind-file')
vim.call('dein#add', 'Shougo/ddu-source-file')
vim.call('dein#add', 'Shougo/ddu-column-filename')

vim.call('dein#end')
vim.call('dein#save_state')

vim.call('ddu#custom#patch_global',
  'uiOptions', {filer = {
    toggle = true,
  }})

vim.call('ddu#custom#patch_global',
  'uiParams', {filer = {
    split ='no',
    toggle = true,
  }})

function ddu_filer_my_settings()
  vim.keymap.set('n', 'o', function()
    if vim.api.nvim_eval('ddu#ui#filer#is_directory()') then
      return "<Cmd>call ddu#ui#filer#do_action('expandItem', {'mode': 'toggle'})<CR>"
    else
      return "<Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'open'})<CR>"
    end
  end, { buffer = true, expr = true })
end

local ddu_filer_groupname = 'ddu-filer-group'
vim.api.nvim_create_augroup(ddu_filer_groupname, { clear = true })
vim.api.nvim_create_autocmd('FileType', {
  group = ddu_filer_groupname,
  pattern = 'ddu-filer',
  callback = ddu_filer_my_settings
})

vim.keymap.set('n', 'e', '<cmd>Ddu -ui=filer -source-option-columns=filename file<CR>', {})

vim.cmd('syntax on')
vim.cmd('filetype on')
vim.cmd('filetype plugin indent on')
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Start Neovim.
2. Run `call dein#update()` command.
3. Restart Neovim.
4. Press the 'e' key.
5. Press the 'o' key on the top item of the 'ddu-ui-filer' displayed.
6. After that, 'ddu-ui-filer' will be inoperable.

## Screenshot (if possible)
![スクリーンショット 2022-08-03 20 34 52](https://user-images.githubusercontent.com/3197942/182598339-2fb4a76d-b9e1-44f1-ad71-a5836da877b2.png)

**Comment by Shougo** [comment]
I have fixed the problem.  Please update ddu.vim.

**Comment by nabezokodaikon** [comment]
If you perform a narrow operation once and then narrow again to the original directory, the current directory will be displayed at the top. Can't this be achieved the first time ddu-filer is started?
![スクリーンショット 2022-08-05 23 44 20](https://user-images.githubusercontent.com/3197942/183101820-4e0a0a8b-3502-423a-a855-1a87a40a43c0.png)

**Comment by nabezokodaikon** [comment]
I saw your dotfiles and solved the problem.
'-source-option-path=`getcwd()`'
So you solve the problem with.

**Comment by Shougo** [comment]
Yes.  You need to set the initial path.
