### ISSUE TITLE
[Question] Is there a way to create a file in the currently selected directory?

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/ddu-ui-filer#8]
Is there a way to create a file in the currently selected directory?

For example, in the following case

![スクリーンショット 2022-08-03 21 39 04](https://user-images.githubusercontent.com/3197942/182609851-8786a76a-2994-42b2-b237-b18f43fea71f.png)

When the cursor is in the vim directory and you create a new file, how do you create a file in the vim directory by just typing the filename, not the full path?

**Comment by Shougo** [comment]
It needs some work.

**Comment by Shougo** [comment]
Please update `ddu-kind-file`.

**Comment by nabezokodaikon** [comment]
Thank you. confirmed.
However, I am worried that the tree display is reset every time I add a file.
Resume is set as follows.
```
Ddu -name=filer -ui=filer -resume -source-option-columns=filename file<CR>
```

**Comment by Shougo** [comment]
Resume does not work for the feature.
Resume means restore the previous state.
But you have changed the directory state.

**Comment by Shougo** [comment]
I have updated `ddu-ui-filer` for it.

**Comment by nabezokodaikon** [comment]
Thank you. confirmed.
